### ISSUE TITLE
task "configure hostname" fail with ansible 2.8.0.dev0

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/ansible-scripts#22]
$ ansible-playbook -u root -l osm312.openstreetmap.fr common.yml
<...>
TASK [common : Configure hostname] *********************************************************************************************************************************************
fatal: [osm312.openstreetmap.fr]: FAILED! => {"changed": false, "msg": "Command failed rc=1, out=, err=Could not get property: Failed to activate service 'org.freedesktop.hostname1': timed out\n"}
$ ansible --version
ansible 2.8.0.dev0

**Comment by gileri** [comment]
Bug `ansible` lié : https://github.com/ansible/ansible/issues/19814

**Comment by Marc-marc-marc** [comment]
testé avec la même version que précédement, extrait du résultat
TASK [common : Check whether systemd-hostnamed is used] ************************************************************************************************************************
ok: [osm312.openstreetmap.fr]

TASK [common : Create override directory for systemd-hostnamed] ****************************************************************************************************************
ok: [osm312.openstreetmap.fr]

TASK [common : Disable PrivateDevices from systemd-hostnamed] ******************************************************************************************************************
ok: [osm312.openstreetmap.fr]

TASK [common : Configure hostname] *********************************************************************************************************************************************
ok: [osm312.openstreetmap.fr]

**Comment by jocelynj** [comment]
Corrigé en enlevant le hostname via 89524f76964723ba16a294e2bcafcf1a7feb68f8.
