### ISSUE TITLE
ajouter real_ip dans le rôle nginx pour les backend

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/ansible-scripts#36]
ajouter quelque chose comme
```
set_real_ip_from 10.0.0.0/24;
real_ip_header X-Forwarded-For;
```
afin que tous les backend aient l'ip réel dans les logs nginx

**Comment by jocelynj** [comment]
Un peu comme https://github.com/osm-fr/ansible-scripts/blob/master/roles/common/templates/apache-remoteip.conf pour apache ?

**Comment by Marc-marc-marc** [comment]
oui
