### ISSUE TITLE
load des vm <> load du host

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/ansible-scripts#52]
Mettre dans ansible la modif lue sur irc comme faite à la main
`modifier la config proxmox pour que le load average vu des VM ne soit pas celui du host mais que celui de la VM
sed -i 's/ExecStart=/usr/bin/lxcfs /var/lib/lxcfs$/ExecStart=/usr/bin/lxcfs /var/lib/lxcfs -l/' /lib/systemd/system/lxcfs.service
mais pour que ce soit actif, il faut stopper toutes les VM, relancer ce service puis les VM... donc bon pour le prochain reboot`

**Comment by jocelynj** [comment]
Je vais plutôt rajouter cette info dans un fichier "/etc/systemd/system/lxcfs.service.d/override.conf", parce que les fichiers dans "/lib/systemd/system/" sont re-écrits lors de la mise à jour de paquets.

**Comment by jocelynj** [comment]
@cquest : pour info, j'ai rajouté cette option `lxcfs -l` dans `/etc/systemd/system/lxcfs.service.d/override.conf`, sur tous les hosts proxmox OSM-FR.
