### ISSUE TITLE
python2 encore nécessaire pour osmose ?

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/ansible-scripts#74]
https://github.com/osm-fr/ansible-scripts/blob/master/roles/osmose-backend/files/README.deb#L7
selon @freed osmose n'utilise plus python2
@jocelynj on vire cette ligne ?

**Comment by jocelynj** [comment]
On peut en fait enlever tous ces packages, qui ne sont plus utilisés. Je m'en occupe.
